using Content.Client.Chat.Managers;
using Content.Client.Message;
using Content.Shared.Chat;
using Content.Shared.Radio;
using Content.Shared.Silicons.Laws;
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Silicons.Laws.Ui;

[GenerateTypedNameReferences]
public sealed partial class LawDisplay : Control
{
    [Dependency] private readonly IChatManager _chatManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly EntityManager _entityManager = default!;

    private static readonly TimeSpan PressCooldown = TimeSpan.FromSeconds(3);

    private readonly Dictionary<Button, TimeSpan> _nextAllowedPress = new();
    private RadioChannelPrototype? _activeRadioChannel;

    public LawDisplay(EntityUid uid, SiliconLaw law, RadioChannelPrototype radioChannelProto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var identifier = law.LawIdentifierOverride ?? $"{law.Order}";
        var lawIdentifier = Loc.GetString("laws-ui-law-header", ("id", identifier));
        var lawDescription = Loc.GetString(law.LawString);
        var lawIdentifierPlaintext = FormattedMessage.RemoveMarkupPermissive(lawIdentifier);
        var lawDescriptionPlaintext = FormattedMessage.RemoveMarkupPermissive(lawDescription);

        LawNumberLabel.SetMarkup(lawIdentifier);
        LawLabel.SetMessage(lawDescription);

        // If you can't talk, you can't state your laws...
        if (!_entityManager.TryGetComponent<SpeechComponent>(uid, out var speech) || speech.SpeechSounds is null)
            return;

        // set up local chat button
        LocalChatButton.Modulate = Color.DarkGray;
        _nextAllowedPress[LocalChatButton] = TimeSpan.Zero;

        LocalChatButton.OnPressed += _ =>
        {
            _chatManager.SendMessage($"{lawIdentifierPlaintext}: {lawDescriptionPlaintext}", ChatSelectChannel.Local);
            _nextAllowedPress[LocalChatButton] = _timing.CurTime + PressCooldown;
        };

        // set up radio channel buttons
        _activeRadioChannel = radioChannelProto;

        RadioChatButton.Text = Loc.GetString(radioChannelProto.Name);
        RadioChatButton.Modulate = radioChannelProto.Color;

        _nextAllowedPress[RadioChatButton] = TimeSpan.Zero;

        RadioChatButton.OnPressed += _ =>
        {
            OnRadioChannelButtonPressed(lawIdentifierPlaintext, lawDescriptionPlaintext);
        };
    }


    private void OnRadioChannelButtonPressed(string lawIdentifierPlaintext, string lawDescriptionPlaintext)
    {
        // this shouldn't happen
        if (_activeRadioChannel is null)
            return;

        // common is slightly different with its prefix, handle this case
        if (_activeRadioChannel == SharedChatSystem.CommonChannel)
        {
            _chatManager.SendMessage($"{SharedChatSystem.RadioCommonPrefix} {lawIdentifierPlaintext}: {lawDescriptionPlaintext}", ChatSelectChannel.Radio);
        }
        else
        {
            _chatManager.SendMessage($"{SharedChatSystem.RadioChannelPrefix}{_activeRadioChannel.KeyCode} {lawIdentifierPlaintext}: {lawDescriptionPlaintext}", ChatSelectChannel.Radio);
        }

        _nextAllowedPress[RadioChatButton] = _timing.CurTime + PressCooldown;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;
        foreach (var (button, nextPress) in _nextAllowedPress)
        {
            button.Disabled = curTime < nextPress;
        }
    }

    public void UpdateSelectedRadioChannel(RadioChannelPrototype radioChannel)
    {
        _activeRadioChannel = radioChannel;

        RadioChatButton.Text = Loc.GetString(radioChannel.Name);
        RadioChatButton.Modulate = radioChannel.Color;
    }
}
