using Content.Client.UserInterface.Controls;
using Content.Shared.Radio;
using Content.Shared.Silicons.Laws.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Silicons.Laws.Ui;

[GenerateTypedNameReferences]
public sealed partial class SiliconLawMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly List<RadioChannelPrototype> _channelPrototypes = [];

    public SiliconLawMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(EntityUid uid, SiliconLawBuiState state)
    {
        state.Laws.Sort();
        LawDisplayContainer.Children.Clear();

        Version.Text = Loc.GetString("laws-window-footer-right", ("version", state.Version));

        if (state.RadioChannels is null)
            return;

        // populate the radio channel dropdown
        foreach (var radioChannel in state.RadioChannels)
        {
            if (!_prototypeManager.TryIndex<RadioChannelPrototype>(radioChannel, out var radioChannelProto))
                continue;

            // make extra sure the ID of the option corresponds to the entry in the list
            var id = _channelPrototypes.Count;
            RadioChannel.AddItem(Loc.GetString(radioChannelProto.Name), id);
            _channelPrototypes.Add(radioChannelProto);
        }

        // this will default to whatever was added first
        var activeRadioChannel = _channelPrototypes[RadioChannel.SelectedId];

        // add law controls
        foreach (var law in state.Laws)
        {
            // these are initialized with the first channel added to the dropdown
            var control = new LawDisplay(uid, law, activeRadioChannel);

            LawDisplayContainer.AddChild(control);
        }

        // propagate channel selection to children
        RadioChannel.OnItemSelected += args =>
        {
            RadioChannel.SelectId(args.Id);

            foreach (var child in LawDisplayContainer.Children)
            {
                if (child is not LawDisplay { } lawDisplay)
                    continue;

                var newRadioChannel = _channelPrototypes[args.Id];

                lawDisplay.UpdateSelectedRadioChannel(newRadioChannel);
            }
        };
    }
}
